name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t your-image-name -f lib/Dockerfile .

    - name: Run Docker container
      run: docker run -d -p 3000:3000 your-image-name npm start
